// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkiiResort.Domain;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(SkiiResortContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "operation_type", new[] { "positive", "negative" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "super_admin", "high_level_admin", "low_level_admin", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkiiResort.Domain.Entities.Location.LocationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Skipass.SkipassRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Skipasses");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Tariff.TariffRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PriceModifier")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Tariffication.TarifficationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TariffId");

                    b.ToTable("Tariffications");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.User.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Visitor.VisitorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.VisitorsAction.VisitorActionsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BalanceChange")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkipassId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SkipassId");

                    b.ToTable("VisitorActions");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Skipass.SkipassRecord", b =>
                {
                    b.HasOne("SkiiResort.Domain.Entities.Tariff.TariffRecord", "Tariff")
                        .WithMany("Skipasses")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkiiResort.Domain.Entities.Visitor.VisitorRecord", "Visitor")
                        .WithMany("Skipasses")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Tariffication.TarifficationRecord", b =>
                {
                    b.HasOne("SkiiResort.Domain.Entities.Location.LocationRecord", "Location")
                        .WithMany("Tariffications")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkiiResort.Domain.Entities.Tariff.TariffRecord", "Tariff")
                        .WithMany("Tariffications")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Visitor.VisitorRecord", b =>
                {
                    b.HasOne("SkiiResort.Domain.Entities.User.UserRecord", "User")
                        .WithOne("Visitor")
                        .HasForeignKey("SkiiResort.Domain.Entities.Visitor.VisitorRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.VisitorsAction.VisitorActionsRecord", b =>
                {
                    b.HasOne("SkiiResort.Domain.Entities.Location.LocationRecord", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkiiResort.Domain.Entities.Skipass.SkipassRecord", "Skipass")
                        .WithMany("VisitorActions")
                        .HasForeignKey("SkipassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Skipass");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Location.LocationRecord", b =>
                {
                    b.Navigation("Tariffications");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Skipass.SkipassRecord", b =>
                {
                    b.Navigation("VisitorActions");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Tariff.TariffRecord", b =>
                {
                    b.Navigation("Skipasses");

                    b.Navigation("Tariffications");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.User.UserRecord", b =>
                {
                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("SkiiResort.Domain.Entities.Visitor.VisitorRecord", b =>
                {
                    b.Navigation("Skipasses");
                });
#pragma warning restore 612, 618
        }
    }
}
